### ISSUE TITLE
ALA Harvest Requires Performance Refactor

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#210]
From @matthewandrews:

DigiVol was down for a few hours on Saturday morning, then again for ~10 min on Sunday morning.  Both resolved with Tomcat restart.  Here's an error from just before last restart at 10.55am Sun:

2016-03-06 10:48:46,054 ERROR [GrailsExceptionResolver] OutOfMemoryError occurred when processing request: [GET] /ws/harvest
GC overhead limit exceeded. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [harvest] of controller [au.org.ala.volunteer.AjaxController]  caused exception: Runtime error executing action
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
    at au.org.ala.volunteer.BVPServletFilter.doFilter(BVPServletFilter.groovy:59)
    at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:44)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
    ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
    ... 11 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
    at au.org.ala.volunteer.AjaxController$_harvesting_closure16.doCall(AjaxController.groovy:390)

**Comment by cdausmus** [comment]
After discussion at team meeting, with separate discussion regarding ALA Harvesting ongoing, closing for now.
/cc @AdamWoodsAM
