### ISSUE TITLE
ALA Dashboard volunteer stats is broken

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/volunteer-portal#336]
Digivol log is showing error for one of the stats
Some stat report query currently logs some error

2019-06-04 00:48:30.768 ERROR --- [io-8080-exec-13] StackTrace                               : Full Stack Trace:

org.springframework.orm.hibernate5.HibernateQueryException: could not resolve property: fullyTranscribedBy of: au.org.ala.volunteer.Task [select t.project.id as projectId, count(t) as taskCount
               from au.org.ala.volunteer.Task t 
               where 
                t.fullyTranscribedBy is not null
                and t.project.inactive != true 
               group by t.project.id]; nested exception is org.hibernate.QueryException: could not resolve property: fullyTranscribedBy of: au.org.ala.volunteer.Task [select t.project.id as projectId, count(t) as taskCount
               from au.org.ala.volunteer.Task t 
               where 
                t.fullyTranscribedBy is not null
                and t.project.inactive != true 
               group by t.project.id]

...
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at au.org.ala.volunteer.TaskService.$tt__getProjectTaskFullyTranscribedCounts(TaskService.groovy:87)
	at au.org.ala.volunteer.TaskService$_getProjectTaskFullyTranscribedCounts_closure7.doCall(TaskService.groovy)
	at sun.reflect.GeneratedMethodAccessor1528.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at au.org.ala.volunteer.TaskService.getProjectTaskFullyTranscribedCounts(TaskService.groovy)
	at au.org.ala.volunteer.TaskService$getProjectTaskFullyTranscribedCounts$1.call(Unknown Source)
	at au.org.ala.volunteer.AjaxController.statsInternal(AjaxController.groovy:81)
	at sun.reflect.GeneratedMethodAccessor1523.invoke(Unknown Source)

**Comment by javier-molina** [comment]
https://support.ehelp.edu.au/a/tickets/34804 relates to this ticket
