### ISSUE TITLE
Index out of bounds exception when selecting random project

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#489]
When selecting a random project, if the last item in the array is selected, the code adds one to the index, and throws an index out of bounds exception: 

```
2021-09-15 00:00:02.510 ERROR --- [o-8080-exec-675] StackTrace                               : Full Stack Trace:

java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at java_util_List$get$5.call(Unknown Source)
        at au.org.ala.volunteer.ProjectService.$tt__selectRandomProject(ProjectService.groovy:953)
        at au.org.ala.volunteer.ProjectService$_selectRandomProject_closure34.doCall(ProjectService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

I can't recall the reason I had added one to the size when generating the random index, maybe remove it.

Also found an issue with the drop down box on the front page edit page not enabling when unchecking the random project checkbox.

**Comment by cdausmus** [comment]
I recall the reason now, it is so that `ThreadLocalRandom.current().nextInt()` wasn't taking 0 and 0 as parameters.

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
