### ISSUE TITLE
New user presented with error 500

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#517]
When a new user attempts to start a new task, they are presented with an error 500.

```
java.lang.NullPointerException: Cannot execute null+[ROLE_USER]
        at org.codehaus.groovy.runtime.NullObject.plus(NullObject.java:135)
        at org.codehaus.groovy.runtime.NullObject$plus$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.NullObject$plus$1.call(Unknown Source)
        at au.org.ala.volunteer.UserService.$tt__hasCasRole(UserService.groovy:374)
        at au.org.ala.volunteer.UserService$_hasCasRole_closure18.doCall(UserService.groovy)
        at sun.reflect.GeneratedMethodAccessor1815.invoke(Unknown Source)
```

**Comment by sbearcsiro** [comment]
Review: LGTM
